version: "3.8"

services:
  vault-dev:
    image: hashicorp/vault:${VAULT_VERSION}
    container_name: vault-dev
    ports:
      - "${VAULT_DEV_PORT}:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_DEV_LISTEN_ADDRESS: ${VAULT_DEV_LISTEN_ADDRESS}
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id="${VAULT_DEV_ROOT_TOKEN_ID}"
    networks:
      - vault-network

networks:
  vault-network:
    driver: bridge
